services:
  anonka-bot:
    build: .
    container_name: anonka-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - DB_PATH=sqlite+aiosqlite:////app/data/data.db
    volumes:
      - ./data:/app/data
    env_file:
      - .env

